import { Challenge } from './types';

export const CHALLENGES: Challenge[] = [
  {
    id: 'glow-up',
    title: 'Glow up challenge',
    description: 'A holistic transformation focusing on daily non-negotiables and weekly resets.\n\nDAILY NON-NEGOTIABLES:\n☐ Wake up at the same time\n☐ No phone for first 30 minutes\n☐ Drink 2–3L water\n☐ Move body (walk / workout / stretch)\n☐ 10 minutes silence or meditation\n☐ Eat at least 1 clean, whole-food meal\n☐ Clean one small area\n☐ Intentional appearance (shower, grooming, outfit)',
    days: [
      { dayNumber: 1, task: 'Write "Who I’m Becoming" manifesto, Clean bedroom, 20 min walk, Early night' },
      { dayNumber: 2, task: 'Delete 5 draining apps/accounts, Journal: habits I’m quitting, Stretch or yoga' },
      { dayNumber: 3, task: '25 min sweaty workout, Eat protein + veg, Clean phone (apps/photos), Posture check all day' },
      { dayNumber: 4, task: '10 min meditation, Journal emotional clutter, Long walk, Wash sheets & towels' },
      { dayNumber: 5, task: 'Do 1 avoided task, 30 min movement, Cold shower (30–60 sec), No complaining today' },
      { dayNumber: 6, task: 'Deep clean one area, Create motivating playlist, Grooming / hair care reset' },
      { dayNumber: 7, task: 'Weekly reflection journal, Light movement, Plan Week 2' },
      { dayNumber: 8, task: 'Write simple daily routine, Strength workout, Power Hour' },
      { dayNumber: 9, task: 'Upgrade meals, 30 min walk, Journal self-respect' },
      { dayNumber: 10, task: 'No multitasking, Finish one task fully, Stretch before bed' },
      { dayNumber: 11, task: 'Harder workout, 3L water, Speak slower & clearly' },
      { dayNumber: 12, task: 'Remove one energy leak, Long walk, Early night' },
      { dayNumber: 13, task: 'Grooming reset (nails, hair, brows), Intentional outfit, Positive mirror talk' },
      { dayNumber: 14, task: 'Review Week 2 wins, Light movement, Plan Week 3' },
      { dayNumber: 15, task: 'Shadow work journaling, Intense workout or long walk, Long shower reset' },
      { dayNumber: 16, task: 'Walk with confidence, Eye contact practice, Strength workout' },
      { dayNumber: 17, task: 'Clean brushes/tools, Body exfoliation, Stretch session' },
      { dayNumber: 18, task: 'Learn 30–60 min, Create something, Journal insights' },
      { dayNumber: 19, task: 'Workout despite resistance, Cold shower, Gratitude list (5)' },
      { dayNumber: 20, task: 'Reach out to supportive person, No gossip, Light movement' },
      { dayNumber: 21, task: 'Write "This is who I am now", Dress well on purpose, Plan final week' },
      { dayNumber: 22, task: 'Do something uncomfortable, Workout, Speak confidently' },
      { dayNumber: 23, task: '5 non-negotiables before noon, High-protein meals, 8 hours sleep' },
      { dayNumber: 24, task: 'Slow everything down, Deep breathing breaks, Minimal screen time' },
      { dayNumber: 25, task: 'Choose signature look, New scent or grooming upgrade, Note reactions' },
      { dayNumber: 26, task: 'Finish a task old-you would quit, Sweat hard, Journal pride moment' },
      { dayNumber: 27, task: 'Compare Day 1 vs now, Write "never again" list, Long walk' },
      { dayNumber: 28, task: 'Go out put-together, Speak less, observe more, Confident posture' },
      { dayNumber: 29, task: 'Gratitude journaling, Light workout, Early night' },
      { dayNumber: 30, task: 'Read original manifesto, Rewrite it at a higher standard, Celebrate without sabotaging' }
    ]
  },
  {
    id: 'meditation',
    title: '30-Day 5-Minute Meditation',
    description: 'Build a daily mindfulness habit with morning and night sessions.',
    days: [
      { dayNumber: 1, task: 'Morning: Wake up & breathe, Night: Let the day settle' },
      { dayNumber: 2, task: 'Morning: Calm breathing, Night: Slow breathing for sleep' },
      { dayNumber: 3, task: 'Morning: Ground your body, Night: Feel safe & supported' },
      { dayNumber: 4, task: 'Morning: Gentle gratitude, Night: Gratitude before sleep' },
      { dayNumber: 5, task: 'Morning: Mini body scan, Night: Body scan for sleep' },
      { dayNumber: 6, task: 'Morning: Release tension, Night: Let go of the day' },
      { dayNumber: 7, task: 'Morning: Calm start, Night: Deep calm sleep' },
      { dayNumber: 8, task: 'Morning: Self-compassion, Night: Kind words before sleep' },
      { dayNumber: 9, task: 'Morning: Calm anxiety, Night: Anxiety release sleep' },
      { dayNumber: 10, task: 'Morning: Gentle confidence boost, Night: Reassurance & safety' },
      { dayNumber: 11, task: 'Morning: Clear focus, Night: Quiet the mind' },
      { dayNumber: 12, task: 'Morning: Emotional balance, Night: Emotional release sleep' },
      { dayNumber: 13, task: 'Morning: Accept what is, Night: Peace with the day' },
      { dayNumber: 14, task: 'Morning: Reset & refresh, Night: Full mental reset' },
      { dayNumber: 15, task: 'Morning: Be here now, Night: Drift into now' },
      { dayNumber: 16, task: 'Morning: Watch thoughts, Night: Thoughts slowing down' },
      { dayNumber: 17, task: 'Morning: Breath focus, Night: Breath to sleep' },
      { dayNumber: 18, task: 'Morning: Inner calm, Night: Peaceful sleep' },
      { dayNumber: 19, task: 'Morning: Cultivating patience, Night: Soft patience' },
      { dayNumber: 20, task: 'Morning: Trust yourself, Night: Safe & supported' },
      { dayNumber: 21, task: 'Morning: Minimal guidance, Night: Near-silent sleep' },
      { dayNumber: 22, task: 'Morning: Gentle energy, Night: Energy release' },
      { dayNumber: 23, task: 'Morning: Inner guidance, Night: Trust & rest' },
      { dayNumber: 24, task: 'Morning: Steady confidence, Night: Ease into sleep' },
      { dayNumber: 25, task: 'Morning: Release stress, Night: Melt stress away' },
      { dayNumber: 26, task: 'Morning: Gentle resilience, Night: Emotional safety' },
      { dayNumber: 27, task: 'Morning: Compassion for self & others, Night: Loving-kindness sleep' },
      { dayNumber: 28, task: 'Morning: Deep stillness, Night: Floating into sleep' },
      { dayNumber: 29, task: 'Morning: Gentle reflection, Night: Appreciation' },
      { dayNumber: 30, task: 'Morning: Completion & gratitude, Night: Rest in achievement' }
    ]
  },
  {
    id: 'screen-free',
    title: '30-Day Screen-Free',
    description: 'Reduce digital clutter and reconnect with the physical world.',
    days: [
      { dayNumber: 1, task: 'Notice: Write down when you want to reach for your phone today' },
      { dayNumber: 2, task: 'Morning Without Screens: First 30 minutes after waking = no screens' },
      { dayNumber: 3, task: 'One Screen-Free Meal: Eat one full meal with no phone, TV, or scrolling' },
      { dayNumber: 4, task: 'Replace the Habit: Swap 10 minutes of scrolling for reading or doodling' },
      { dayNumber: 5, task: 'Walk Without Distraction: 10–20 min walk, no podcasts, no music' },
      { dayNumber: 6, task: 'Hands Busy: Do something tactile like cooking or cleaning' },
      { dayNumber: 7, task: 'Mini Reset: Journal what was harder than expected and what felt nice' },
      { dayNumber: 8, task: 'Screen-Free Hour: Choose one full hour after dinner with no screens' },
      { dayNumber: 9, task: 'Boredom Practice: Sit for 5–10 minutes doing nothing' },
      { dayNumber: 10, task: 'Music Only: Play music — no visuals, lie down or potter around' },
      { dayNumber: 11, task: 'Analog Comfort: Do one cozy thing like candle + book' },
      { dayNumber: 12, task: 'Write It Out: Write a letter or journal' },
      { dayNumber: 13, task: 'Early Night: Screens off 1 hour before bed' },
      { dayNumber: 14, task: 'Check-In: Reflect on sleep, mood, and attention span' },
      { dayNumber: 15, task: 'Single-Tasking: Do one thing at a time on purpose' },
      { dayNumber: 16, task: 'Nature Touch: Touch something natural like grass or leaves' },
      { dayNumber: 17, task: 'Screen-Free Social Time: Talk to someone with no phones present' },
      { dayNumber: 18, task: 'Create Something: Draw, cook, write, build' },
      { dayNumber: 19, task: 'News Fast: No news or social media today' },
      { dayNumber: 20, task: 'Slow Morning: Wake up slower than usual, no rushing' },
      { dayNumber: 21, task: 'Reflection Day: What do I miss? What do I not miss?' },
      { dayNumber: 22, task: 'App Boundaries: Delete one unnecessary app' },
      { dayNumber: 23, task: 'Intentional Screen Time: Choose a specific time to use screens' },
      { dayNumber: 24, task: 'Replace Night Scrolling: Choose a new wind-down habit' },
      { dayNumber: 25, task: 'Half-Day Screen-Light: Spend half the day avoiding non-essential screens' },
      { dayNumber: 26, task: 'Reclaim Waiting Time: No phone while waiting in queues or bus stops' },
      { dayNumber: 27, task: 'Digital Declutter: Clean photos, emails, notes, open tabs' },
      { dayNumber: 28, task: 'Full Screen-Free Evening: From dinner to bed = no screens' },
      { dayNumber: 29, task: 'Choose Your Rules: Decide what screens are actually helpful' },
      { dayNumber: 30, task: 'Closing Ritual: Reflect on what changed and what you will keep' }
    ]
  },
  {
    id: 'sleep-reset',
    title: '30-Day Sleep Reset',
    description: 'Optimize your sleep hygiene for better rest and energy.',
    days: [
      { dayNumber: 1, task: 'Your Baseline: Write down sleep times and how rested you feel' },
      { dayNumber: 2, task: 'Consistent Wake-Up Time: Wake up at the same time (±30 min)' },
      { dayNumber: 3, task: 'Morning Light: Get 5–10 minutes of daylight within an hour of waking' },
      { dayNumber: 4, task: 'Caffeine Check: No caffeine after 2pm' },
      { dayNumber: 5, task: 'Bed = Sleep: Use your bed only for sleep, rest, and intimacy' },
      { dayNumber: 6, task: 'Wind-Down Window: Choose a 15–30 min pre-bed wind-down time' },
      { dayNumber: 7, task: 'Weekly Reflection: Note what helped and what didn’t' },
      { dayNumber: 8, task: 'Screen Softening: Dim screens or use night mode after sunset' },
      { dayNumber: 9, task: 'Body Relaxation: Do 5 minutes of stretching or gentle yoga' },
      { dayNumber: 10, task: 'Brain Dump: Write down everything in your head before bed' },
      { dayNumber: 11, task: 'Temperature Check: Aim for a slightly cooler sleep space' },
      { dayNumber: 12, task: 'Breathing for Sleep: Try inhale 4, exhale 4 for 3–5 minutes' },
      { dayNumber: 13, task: 'Consistent Bedtime: Choose a bedtime range (±30 min)' },
      { dayNumber: 14, task: 'Midpoint Reset: Reflect on falling asleep faster and rested mornings' },
      { dayNumber: 15, task: 'Move Your Body: 10–30 minutes of movement' },
      { dayNumber: 16, task: 'Nap Audit: Keep naps under 30 min and before 3pm' },
      { dayNumber: 17, task: 'Sun + Movement Combo: Walk outside during daylight hours' },
      { dayNumber: 18, task: 'Alcohol Awareness: Notice how alcohol affects your sleep' },
      { dayNumber: 19, task: 'Stress Release: Journaling, crying, talking, or stretching' },
      { dayNumber: 20, task: 'Evening Boundaries: No heavy problem-solving at night' },
      { dayNumber: 21, task: 'Sleep Beliefs Check: Replace negative sleep thoughts with positive ones' },
      { dayNumber: 22, task: 'Comfort Upgrade: Improve pillow, sheets, or lighting' },
      { dayNumber: 23, task: 'Quiet Evenings: Lower lights & noise after dinner' },
      { dayNumber: 24, task: 'If You Wake at Night: Get up if awake >20 min, do calm activity' },
      { dayNumber: 25, task: 'Evening Ritual: Create a simple bedtime ritual' },
      { dayNumber: 26, task: 'Reduce Clock Watching: Turn the clock away' },
      { dayNumber: 27, task: 'Safe Thoughts: Choose a calming mental focus' },
      { dayNumber: 28, task: 'Screen-Free Wind-Down: No screens for 1 hour before bed' },
      { dayNumber: 29, task: 'Your Sleep Rules: Decide ideal bedtime and wake time' },
      { dayNumber: 30, task: 'Review & Celebrate: Reflect on what improved and stuck' }
    ]
  },
  {
    id: 'self-discovery',
    title: '30-Day Self-Discovery',
    description: 'Explore who you are through daily reflection prompts.',
    days: [
      { dayNumber: 1, task: 'Life Snapshot: How do I feel about my life right now?' },
      { dayNumber: 2, task: 'Energy Audit: List 3 things that drain and 3 that energise me' },
      { dayNumber: 3, task: 'Values Check: What matters to me even when it’s hard?' },
      { dayNumber: 4, task: 'Roles I Play: Write down the roles you carry' },
      { dayNumber: 5, task: 'Emotional Patterns: What emotions show up most often?' },
      { dayNumber: 6, task: 'Body Signals: Notice when your body tenses or relaxes' },
      { dayNumber: 7, task: 'Reflection: This week I learned... I’m starting to notice...' },
      { dayNumber: 8, task: 'Younger You: What did you love as a child? What did you need?' },
      { dayNumber: 9, task: 'Survival Skills: What coping habits helped you survive?' },
      { dayNumber: 10, task: 'Repeating Themes: What situations keep repeating in your life?' },
      { dayNumber: 11, task: 'Unspoken Rules: What "rules" did you grow up with?' },
      { dayNumber: 12, task: 'Boundaries: Where do you say yes when you mean no?' },
      { dayNumber: 13, task: 'Self-Talk: Notice your inner voice today' },
      { dayNumber: 14, task: 'Integration: What makes more sense now? What to release?' },
      { dayNumber: 15, task: 'Wants vs Shoulds: List things I want vs things I think I should want' },
      { dayNumber: 16, task: 'Joy Clues: When do I lose track of time?' },
      { dayNumber: 17, task: 'Ideal Day: Describe a realistic "good day" in detail' },
      { dayNumber: 18, task: 'Strengths: What comes naturally to me?' },
      { dayNumber: 19, task: 'Fear Inventory: What am I afraid of losing or becoming?' },
      { dayNumber: 20, task: 'Meaning: What makes life feel meaningful to me?' },
      { dayNumber: 21, task: 'Direction Check: If nothing changed for a year, how would I feel?' },
      { dayNumber: 22, task: 'Values in Action: How do daily choices align with values?' },
      { dayNumber: 23, task: 'Boundaries I Need: One boundary I need more of' },
      { dayNumber: 24, task: 'Self-Trust: When have I trusted myself before and been okay?' },
      { dayNumber: 25, task: 'Letting Go: What am I ready to stop carrying?' },
      { dayNumber: 26, task: 'Becoming Statement: "I am becoming someone who..."' },
      { dayNumber: 27, task: 'Support: What support do I need more of?' },
      { dayNumber: 28, task: 'Gentle Vision: Where do I want to be emotionally in 6 months?' },
      { dayNumber: 29, task: 'Commitments: What small promises can I keep to myself?' },
      { dayNumber: 30, task: 'Closing Reflection: What surprised me? What stayed true?' }
    ]
  },
  {
    id: 'inner-child',
    title: '30 Days of Inner Child Care',
    description: 'Rebuilding safety, joy, and trust with the younger you.',
    days: [
      { dayNumber: 1, task: 'Write a note to your younger self' },
      { dayNumber: 2, task: 'Do something comforting from childhood' },
      { dayNumber: 3, task: 'Eat a food that feels safe or nostalgic' },
      { dayNumber: 4, task: 'Notice when you’re hard on yourself — soften it' },
      { dayNumber: 5, task: 'Rest without earning it' },
      { dayNumber: 6, task: 'Create a "safe place" visualization' },
      { dayNumber: 7, task: 'Reflect: What does my inner child need most?' },
      { dayNumber: 8, task: 'Ask: "What am I feeling right now?"' },
      { dayNumber: 9, task: 'Let yourself play (draw, dance, be silly)' },
      { dayNumber: 10, task: 'Speak kindly to yourself out loud' },
      { dayNumber: 11, task: 'Honour a boundary you needed as a child' },
      { dayNumber: 12, task: 'Notice when you shrink — gently don’t' },
      { dayNumber: 13, task: 'Write what younger you wanted adults to know' },
      { dayNumber: 14, task: 'Check-in: what’s changed?' },
      { dayNumber: 15, task: 'Say no to one small thing' },
      { dayNumber: 16, task: 'Advocate for yourself (even privately)' },
      { dayNumber: 17, task: 'Let yourself feel without fixing' },
      { dayNumber: 18, task: 'Create something with no goal' },
      { dayNumber: 19, task: 'Comfort yourself when emotions rise' },
      { dayNumber: 20, task: 'Remind yourself: "I’m safe now"' },
      { dayNumber: 21, task: 'Reflect: how am I showing up differently?' },
      { dayNumber: 22, task: 'Do something just for joy' },
      { dayNumber: 23, task: 'Notice when you self-abandon — return' },
      { dayNumber: 24, task: 'Keep one promise to yourself' },
      { dayNumber: 25, task: 'Let go of a childhood belief that no longer fits' },
      { dayNumber: 26, task: 'Celebrate who you survived being' },
      { dayNumber: 27, task: 'Practice gentleness under stress' },
      { dayNumber: 28, task: 'Write a thank-you to yourself' },
      { dayNumber: 29, task: 'Choose one inner-child ritual to keep' },
      { dayNumber: 30, task: 'Closing reflection & rest' }
    ]
  },
  {
    id: 'becoming',
    title: '30 Days of Becoming',
    description: 'Small daily choices toward who you’re becoming.',
    days: [
      { dayNumber: 1, task: 'Who am I becoming right now?' },
      { dayNumber: 2, task: 'What drains vs nourishes me?' },
      { dayNumber: 3, task: 'Notice one aligned choice' },
      { dayNumber: 4, task: 'Notice one misaligned choice (no shame)' },
      { dayNumber: 5, task: 'Clarify one value' },
      { dayNumber: 6, task: 'Choose based on feeling, not fear' },
      { dayNumber: 7, task: 'Reflect on patterns' },
      { dayNumber: 8, task: 'Choose rest over pressure' },
      { dayNumber: 9, task: 'Choose honesty over pleasing' },
      { dayNumber: 10, task: 'Choose curiosity over judgment' },
      { dayNumber: 11, task: 'Choose slower' },
      { dayNumber: 12, task: 'Choose self-respect' },
      { dayNumber: 13, task: 'Choose consistency over intensity' },
      { dayNumber: 14, task: 'Check-in: what feels different?' },
      { dayNumber: 15, task: 'Act like the person you’re becoming (small)' },
      { dayNumber: 16, task: 'Speak like them' },
      { dayNumber: 17, task: 'Care for your body like them' },
      { dayNumber: 18, task: 'Set a boundary like them' },
      { dayNumber: 19, task: 'Make one brave micro-choice' },
      { dayNumber: 20, task: 'Rest like someone who trusts themselves' },
      { dayNumber: 21, task: 'Reflect on identity shifts' },
      { dayNumber: 22, task: 'Let go of an old version of you' },
      { dayNumber: 23, task: 'Trust your timing' },
      { dayNumber: 24, task: 'Choose patience' },
      { dayNumber: 25, task: 'Choose compassion for setbacks' },
      { dayNumber: 26, task: 'Name what you’re proud of' },
      { dayNumber: 27, task: 'Decide what stays' },
      { dayNumber: 28, task: 'Decide what goes' },
      { dayNumber: 29, task: 'Write a becoming statement' },
      { dayNumber: 30, task: 'Honour the transition' }
    ]
  },
  {
    id: 'mind-body',
    title: '30 Days of Mind–Body Connection',
    description: 'Learning to listen to your body instead of overriding it.',
    days: [
      { dayNumber: 1, task: 'Body scan' },
      { dayNumber: 2, task: 'Notice tension' },
      { dayNumber: 3, task: 'Notice breath' },
      { dayNumber: 4, task: 'Notice hunger & fullness' },
      { dayNumber: 5, task: 'Notice fatigue' },
      { dayNumber: 6, task: 'Notice comfort' },
      { dayNumber: 7, task: 'Reflect' },
      { dayNumber: 8, task: 'Stretch when stiff' },
      { dayNumber: 9, task: 'Rest when tired' },
      { dayNumber: 10, task: 'Breathe when overwhelmed' },
      { dayNumber: 11, task: 'Eat when hungry' },
      { dayNumber: 12, task: 'Pause before pushing' },
      { dayNumber: 13, task: 'Move intuitively' },
      { dayNumber: 14, task: 'Check-in' },
      { dayNumber: 15, task: 'Grounding exercise' },
      { dayNumber: 16, task: 'Gentle movement' },
      { dayNumber: 17, task: 'Temperature awareness' },
      { dayNumber: 18, task: 'Self-soothing practice' },
      { dayNumber: 19, task: 'Emotional-body link' },
      { dayNumber: 20, task: 'Slow breathing' },
      { dayNumber: 21, task: 'Reflect' },
      { dayNumber: 22, task: 'Ask your body what it needs' },
      { dayNumber: 23, task: 'Honour one physical boundary' },
      { dayNumber: 24, task: 'Rest without guilt' },
      { dayNumber: 25, task: 'Move for pleasure' },
      { dayNumber: 26, task: 'Speak kindly to your body' },
      { dayNumber: 27, task: 'Choose comfort intentionally' },
      { dayNumber: 28, task: 'Notice safety signals' },
      { dayNumber: 29, task: 'Write body wisdom' },
      { dayNumber: 30, task: 'Integration & gratitude' }
    ]
  },
  {
    id: 'living-softer',
    title: '30 Days of Living Softer',
    description: 'Embrace a slower, more intentional pace of life.',
    days: [
      { dayNumber: 1, task: 'Do one thing slowly' },
      { dayNumber: 2, task: 'Speak slower' },
      { dayNumber: 3, task: 'Eat slower' },
      { dayNumber: 4, task: 'Walk slower' },
      { dayNumber: 5, task: 'Breathe slower' },
      { dayNumber: 6, task: 'Rest longer' },
      { dayNumber: 7, task: 'Reflect' },
      { dayNumber: 8, task: 'Do less today' },
      { dayNumber: 9, task: 'Say no to rushing' },
      { dayNumber: 10, task: 'Drop one unnecessary task' },
      { dayNumber: 11, task: 'Lower expectations' },
      { dayNumber: 12, task: 'Stop explaining yourself' },
      { dayNumber: 13, task: 'Cancel something optional' },
      { dayNumber: 14, task: 'Check-in' },
      { dayNumber: 15, task: 'Create coziness' },
      { dayNumber: 16, task: 'Choose softness (clothes, lighting)' },
      { dayNumber: 17, task: 'Comfort over productivity' },
      { dayNumber: 18, task: 'Gentle movement' },
      { dayNumber: 19, task: 'Kind inner voice' },
      { dayNumber: 20, task: 'Early night' },
      { dayNumber: 21, task: 'Reflect' },
      { dayNumber: 22, task: 'Protect your energy' },
      { dayNumber: 23, task: 'Do nothing on purpose' },
      { dayNumber: 24, task: 'Let life meet you' },
      { dayNumber: 25, task: 'Trust ease' },
      { dayNumber: 26, task: 'Release urgency' },
      { dayNumber: 27, task: 'Live at your pace' },
      { dayNumber: 28, task: 'Choose what feels kind' },
      { dayNumber: 29, task: 'Decide what softness looks like for you' },
      { dayNumber: 30, task: 'Commit to living gentler' }
    ]
  }
];

export const PROMPTS = [
  { id: 'p1', text: 'What made you smile today?', category: 'Gratitude' },
  { id: 'p2', text: 'What is one thing you are proud of yourself for?', category: 'Self-Reflection' },
  { id: 'p3', text: 'How did you handle a challenge today?', category: 'Growth' },
  { id: 'p4', text: 'What is a small win you had today?', category: 'Gratitude' },
  { id: 'p5', text: 'What is something you are looking forward to?', category: 'Hope' }
];
